export enum Category {
    // Define the possible values for the Category enum
    DEEP_HOUSE = 'DEEP_HOUSE',
    TECH_HOUSE = 'Tech House',
    PROGRESSIVE_HOUSE = 'Progressive House',
    ELECTRO_HOUSE = 'Electro House',
    DETROIT_TECHNO = 'Detroit Techno',
    MINIMAL_TECHNO = 'Minimal Techno',
    ACID_TECHNO = 'Acid Techno',
    TRANCE = 'Trance',
    PROGRESSIVE_TRANCE = 'Progressive Trance',
    DRUM_AND_BASS = 'Drum and Bass',
    JUNGLE = 'Jungle',
    NU_SKOOL_BREAKS = 'Nu Skool Breaks',
    BIG_BEAT = 'Big Beat',
    DUBSTEP = 'Dubstep',
    HARDCORE = 'Hardcore',
    AMBIENT = 'Ambient',
    EXPERIMENTAL = 'Experimental',
}